#!/usr/bin/env bash
#
# Regenerate geoip/<cc>.txt CIDR lists used by `geoip:<cc>` routing rules.
#
#   scripts/update-geoip.sh            # default: ir
#   scripts/update-geoip.sh ir ru cn   # specific country codes
#
# Sources:
#   - arastu/mikrotik-iran-address-list (ir only) — aggregates RIPE + ipdeny +
#     more and is itself auto-updated; the most complete Iran list.
#   - RIPE NCC country-resource-list — authoritative, works for any cc.
# The union is filtered to valid IPv4 CIDRs and de-duplicated.
#
set -euo pipefail
cd "$(dirname "$0")/.."
mkdir -p geoip

ccs=("$@")
[ ${#ccs[@]} -eq 0 ] && ccs=(ir)

for cc in "${ccs[@]}"; do
  lc=$(printf '%s' "$cc" | tr '[:upper:]' '[:lower:]')
  uc=$(printf '%s' "$cc" | tr '[:lower:]' '[:upper:]')
  tmp=$(mktemp)

  if [ "$lc" = "ir" ]; then
    curl -fsSL --max-time 60 \
      "https://raw.githubusercontent.com/arastu/mikrotik-iran-address-list/main/dist/iran-ips.txt" \
      >> "$tmp" 2>/dev/null || echo "warn: arastu fetch failed for $lc" >&2
  fi

  curl -fsSL --max-time 60 \
    "https://stat.ripe.net/data/country-resource-list/data.json?resource=${uc}" \
    2>/dev/null \
    | grep -oE '"[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[0-9]+"' | tr -d '"' \
    >> "$tmp" 2>/dev/null || echo "warn: RIPE fetch failed for $uc" >&2

  out="geoip/${lc}.txt"
  {
    echo "# geoip CIDR list for ${uc} — generated by scripts/update-geoip.sh"
    echo "# sources: arastu/mikrotik-iran-address-list (ir), RIPE country-resource-list"
    grep -oE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[0-9]+$' "$tmp" | sort -u
  } > "$out"
  rm -f "$tmp"
  echo "$out: $(grep -cE '^[0-9]' "$out") CIDRs"
done
