// Package backup zips moav-client's persistent state (config.yaml + data/)
// for export, and restores it on upload. Excludes runtime artifacts the
// caller doesn't actually need: state.json, generated sing-box / xray
// configs, the sing-box & xray container working dirs.
package backup

import (
	"archive/zip"
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// Exclude lists the file *basenames* (lowercase) we skip during Create.
// state.json is regenerated by the prober. singbox.json / xray.json are
// regenerated by main.go on startup. sidecar-configs/ holds per-container
// runtime config that's also regenerated.
var Exclude = map[string]bool{
	"state.json":  true,
	"singbox.json": true,
	"xray.json":    true,
	".env":         false, // user state — KEEP it (so exposure / auth survives a restore)
	".tmp":         true,
}

// Create returns a zip archive containing config.yaml plus everything under
// data/ that isn't in Exclude or inside sidecar-configs/.
func Create(installRoot string) ([]byte, error) {
	var buf bytes.Buffer
	w := zip.NewWriter(&buf)
	defer w.Close()

	add := func(rel string) error {
		full := filepath.Join(installRoot, rel)
		info, err := os.Stat(full)
		if err != nil {
			if os.IsNotExist(err) {
				return nil
			}
			return err
		}
		if info.IsDir() {
			return filepath.Walk(full, func(p string, fi os.FileInfo, err error) error {
				if err != nil {
					return err
				}
				if fi.IsDir() {
					return nil
				}
				rp, _ := filepath.Rel(installRoot, p)
				return addFile(w, p, rp)
			})
		}
		return addFile(w, full, rel)
	}

	if err := add("config.yaml"); err != nil {
		return nil, err
	}
	if err := add(".env"); err != nil {
		return nil, err
	}
	if err := add("data"); err != nil {
		return nil, err
	}

	if err := w.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func addFile(w *zip.Writer, srcAbs, relPath string) error {
	base := strings.ToLower(filepath.Base(relPath))
	if Exclude[base] {
		return nil
	}
	// Skip the runtime sidecar-configs tree — those are regenerated on every
	// startup from the parameters declared in config.yaml.
	if strings.HasPrefix(filepath.ToSlash(relPath), "data/sidecar-configs/") {
		return nil
	}

	f, err := os.Open(srcAbs)
	if err != nil {
		return err
	}
	defer f.Close()

	wr, err := w.Create(relPath)
	if err != nil {
		return err
	}
	_, err = io.Copy(wr, f)
	return err
}

// Restore extracts a moav-client backup zip into installRoot, overwriting
// any existing config.yaml / data/ files. Like the bundles package, we
// reject any entry whose name would escape via ".." or be absolute.
func Restore(installRoot string, zipBytes []byte) (count int, err error) {
	r, err := zip.NewReader(bytes.NewReader(zipBytes), int64(len(zipBytes)))
	if err != nil {
		return 0, fmt.Errorf("invalid zip: %w", err)
	}
	for _, f := range r.File {
		if f.FileInfo().IsDir() {
			continue
		}
		if filepath.IsAbs(f.Name) ||
			strings.HasPrefix(f.Name, "../") ||
			strings.Contains(f.Name, "/../") {
			continue
		}
		clean := filepath.Clean(f.Name)
		if strings.HasPrefix(clean, "..") {
			continue
		}
		out := filepath.Join(installRoot, clean)
		if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
			return count, err
		}
		rc, err := f.Open()
		if err != nil {
			return count, err
		}
		body, err := io.ReadAll(rc)
		rc.Close()
		if err != nil {
			return count, err
		}
		if err := os.WriteFile(out, body, 0o644); err != nil {
			return count, err
		}
		count++
	}
	return count, nil
}
